# Determine if GWANN can build and run
on:
  push:
  pull_request:

name: run

jobs:
  run:

    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - name: get
        run: ./get.sh

      - name: run
        run: ./genome-linux-64bit -pop 2 -N 3 -tree

